### PR TITLE
Simplify and optimize routing

### PR DESCRIPTION
**Pull request by matthewmcgarvey**
## Main Optimizations

- Check http method last instead of first (moved from Matcher to Fragment)
- Use a loop in MatchFinder rather than recursion
- Drop hash in Matcher for a single root Fragment

## Other Changes

- Update benchmark to find an average of multiple runs for more accurate times
- Refactoring around MatchFinder and Fragment to simplify logic

## Performance Improvement

With the updated benchmark in this PR, I found that master currently finishes the benchmark with an average of 10.9 milliseconds. Running the benchmark with this PR returns an average of 6.8 milliseconds

- Old: 10.9 ms
- New: 6.8 ms
- Difference: 4.1 ms
- **Improvement: 38%**

### CODE REVIEW

**Comment by matthewmcgarvey** [comment]
I'd like to run this change through a [benchmark](https://github.com/the-benchmarker/web-frameworks/tree/cloudify#results) to see what happens but I wasn't able to get it going locally

**Comment by jwoertink** [comment]
Dude! This is amazing! It's kind of a gnarly PR, so might take a bit to really go through, but my initial thought is it's probably fine. Thanks for tackling this!

**Comment by matthewmcgarvey** [comment]
@jwoertink I'm going to break down this PR so we can capture each change individually since it's really at least 3 changes

**Comment by paulcsmith** [comment]
That sounds great. Thanks!

**Pull request closed without merging**
